### PR TITLE
skip visiting anonymous classes

### LINKED ISSUE #71: Fix anonymous classes
The deprecation detector crashes if anonymous classes are used.

Part of PHPUnit that lets the detector break ([original file](https://github.com/sebastianbergmann/php-token-stream/blob/master/tests/_fixture/class_with_method_that_declares_anonymous_class.php)).
```php
$o = new class { public function foo() {} };
$o = new class{public function foo(){}};
$o = new class extends stdClass {};
$o = new class extends stdClass {};
$o = new class implements foo {};
```
Some classes try to access the `name` or `namespacedName` attribute of an AST class node and generate an `Usage` with that name.
Because the `namespacedName` is no longer provided if the node is an anonymous class the issue occurs.

e.g `FindDeprecatedTagsVisitor` in line 44
```php
public function enterNode(Node $node)
{
    if ($node instanceof Node\Stmt\ClassLike) {
        $this->parentName = $node->namespacedName->toString();
    }

    ...
}
```

As `$node->namespacedName` is not provided anymore in any class  

```
PHP Notice:  Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName in /vagrant/www/contrib/deprecation-detector/src/Visitor/Deprecation/FindDeprecatedTagsVisitor.php on line 44
PHP Stack trace:
PHP   1. {main}() /vagrant/www/contrib/deprecation-detector/bin/deprecation-detector:0
PHP   2. Symfony\Component\Console\Application->run() /vagrant/www/contrib/deprecation-detector/bin/deprecation-detector:18
PHP   3. Symfony\Component\Console\Application->doRun() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:886
PHP   6. SensioLabs\DeprecationDetector\Console\Command\CheckCommand->execute() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Command/Command.php:259
PHP   7. SensioLabs\DeprecationDetector\Detector\ViolationDetector->getViolations() /vagrant/www/contrib/deprecation-detector/src/Console/Command/CheckCommand.php:144
PHP   8. SensioLabs\DeprecationDetector\Finder\ParsedPhpFileFinder->getIterator() /vagrant/www/contrib/deprecation-detector/src/Console/Command/CheckCommand.php:45
PHP   9. SensioLabs\DeprecationDetector\Parser\UsageParser->parseFile() /vagrant/www/contrib/deprecation-detector/src/Finder/ParsedPhpFileFinder.php:49
PHP  10. PhpParser\NodeTraverser->traverse() /vagrant/www/contrib/deprecation-detector/src/Parser/UsageParser.php:70
PHP  11. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:64
PHP  12. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  13. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  14. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  15. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  16. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  17. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  18. SensioLabs\DeprecationDetector\Visitor\Deprecation\FindDeprecatedTagsVisitor->enterNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88

Notice: Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName in /vagrant/www/contrib/deprecation-detector/src/Visitor/Deprecation/FindDeprecatedTagsVisitor.php on line 44

Call Stack:
    0.0006     224152   1. {main}() /vagrant/www/contrib/deprecation-detector/bin/deprecation-detector:0
    0.2352    2014264   2. Symfony\Component\Console\Application->run() /vagrant/www/contrib/deprecation-detector/bin/deprecation-detector:18
    0.3031    2359816   3. Symfony\Component\Console\Application->doRun() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:126
    0.3033    2360736   4. Symfony\Component\Console\Application->doRunCommand() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:195
    0.3278    2431448   5. Symfony\Component\Console\Command\Command->run() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:886
    0.3285    2436536   6. SensioLabs\DeprecationDetector\Console\Command\CheckCommand->execute() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Command/Command.php:259
   52.5725   12499048   7. SensioLabs\DeprecationDetector\Detector\ViolationDetector->getViolations() /vagrant/www/contrib/deprecation-detector/src/Console/Command/CheckCommand.php:144
   59.7791   12500712   8. SensioLabs\DeprecationDetector\Finder\ParsedPhpFileFinder->getIterator() /vagrant/www/contrib/deprecation-detector/src/Console/Command/CheckCommand.php:45
  136.1687   27920912   9. SensioLabs\DeprecationDetector\Parser\UsageParser->parseFile() /vagrant/www/contrib/deprecation-detector/src/Finder/ParsedPhpFileFinder.php:49
  136.1840   28011408  10. PhpParser\NodeTraverser->traverse() /vagrant/www/contrib/deprecation-detector/src/Parser/UsageParser.php:70
  136.1840   28010328  11. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:64
  136.1844   28016784  12. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
  136.1844   28019672  13. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
  136.1846   28021160  14. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
  136.1846   28024040  15. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
  136.1847   28025880  16. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
  136.1850   28028536  17. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
  136.1850   28029360  18. SensioLabs\DeprecationDetector\Visitor\Deprecation\FindDeprecatedTagsVisitor->enterNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88

PHP Fatal error:  Call to a member function toString() on a non-object in /vagrant/www/contrib/deprecation-detector/src/Visitor/Deprecation/FindDeprecatedTagsVisitor.php on line 44
PHP Stack trace:
PHP   1. {main}() /vagrant/www/contrib/deprecation-detector/bin/deprecation-detector:0
PHP   2. Symfony\Component\Console\Application->run() /vagrant/www/contrib/deprecation-detector/bin/deprecation-detector:18
PHP   3. Symfony\Component\Console\Application->doRun() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:886
PHP   6. SensioLabs\DeprecationDetector\Console\Command\CheckCommand->execute() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Command/Command.php:259
PHP   7. SensioLabs\DeprecationDetector\Detector\ViolationDetector->getViolations() /vagrant/www/contrib/deprecation-detector/src/Console/Command/CheckCommand.php:144
PHP   8. SensioLabs\DeprecationDetector\Finder\ParsedPhpFileFinder->getIterator() /vagrant/www/contrib/deprecation-detector/src/Console/Command/CheckCommand.php:45
PHP   9. SensioLabs\DeprecationDetector\Parser\UsageParser->parseFile() /vagrant/www/contrib/deprecation-detector/src/Finder/ParsedPhpFileFinder.php:49
PHP  10. PhpParser\NodeTraverser->traverse() /vagrant/www/contrib/deprecation-detector/src/Parser/UsageParser.php:70
PHP  11. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:64
PHP  12. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  13. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  14. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  15. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  16. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  17. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  18. SensioLabs\DeprecationDetector\Visitor\Deprecation\FindDeprecatedTagsVisitor->enterNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88

Fatal error: Call to a member function toString() on a non-object in /vagrant/www/contrib/deprecation-detector/src/Visitor/Deprecation/FindDeprecatedTagsVisitor.php on line 44

Call Stack:
    0.0006     224152   1. {main}() /vagrant/www/contrib/deprecation-detector/bin/deprecation-detector:0
    0.2352    2014264   2. Symfony\Component\Console\Application->run() /vagrant/www/contrib/deprecation-detector/bin/deprecation-detector:18
    0.3031    2359816   3. Symfony\Component\Console\Application->doRun() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:126
    0.3033    2360736   4. Symfony\Component\Console\Application->doRunCommand() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:195
    0.3278    2431448   5. Symfony\Component\Console\Command\Command->run() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Application.php:886
    0.3285    2436536   6. SensioLabs\DeprecationDetector\Console\Command\CheckCommand->execute() /vagrant/www/contrib/deprecation-detector/vendor/symfony/console/Command/Command.php:259
   52.5725   12499048   7. SensioLabs\DeprecationDetector\Detector\ViolationDetector->getViolations() /vagrant/www/contrib/deprecation-detector/src/Console/Command/CheckCommand.php:144
   59.7791   12500712   8. SensioLabs\DeprecationDetector\Finder\ParsedPhpFileFinder->getIterator() /vagrant/www/contrib/deprecation-detector/src/Console/Command/CheckCommand.php:45
  136.1687   27920912   9. SensioLabs\DeprecationDetector\Parser\UsageParser->parseFile() /vagrant/www/contrib/deprecation-detector/src/Finder/ParsedPhpFileFinder.php:49
  136.1840   28011408  10. PhpParser\NodeTraverser->traverse() /vagrant/www/contrib/deprecation-detector/src/Parser/UsageParser.php:70
  136.1840   28010328  11. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:64
  136.1844   28016784  12. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
  136.1844   28019672  13. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
  136.1846   28021160  14. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
  136.1846   28024040  15. PhpParser\NodeTraverser->traverseArray() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
  136.1847   28025880  16. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
  136.1850   28028536  17. PhpParser\NodeTraverser->traverseNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
  136.1850   28029360  18. SensioLabs\DeprecationDetector\Visitor\Deprecation\FindDeprecatedTagsVisitor->enterNode() /vagrant/www/contrib/deprecation-detector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
```

### PR DESCRIPTION
**Pull request by xabbuh**
This fixes #71.

### CODE REVIEW

**Comment by xabbuh** [comment]
Tests should be added if @MarvinKlemp can confirm that this fixes his issue.

**Comment by MarvinKlemp** [comment]
:+1: 

try to run `deprecation-detector check vendor/ vendor/`, there are some more `Visitors` that use `ClassNodes`

**Comment by slde-flash** [comment]
:+1:

**Comment by MarvinKlemp** [comment]
ping @xabbuh

**Comment by xabbuh** [comment]
I need to have a deeper look at how the class name is used in each of these classes. I hope to get my hands onto this this weekend.

**Comment by MarvinKlemp** [comment]
@xabbuh I fixed the error in #86

**Pull request closed without merging**
